# -*- coding: utf-8 -*-
"""exploratory data analysis task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f0wE5ETultsPGOy9FB_oRNtyowQCUuxR
"""

!pip  install  pandas
from kagglehub import KaggleDatasetAdapter

import kagglehub


import pandas as pd

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load dataset
df = sns.load_dataset('titanic')

# Summary statistics
summary = df.describe(include='all')
print(summary)

# Histogram for Age
df['age'].hist(bins=30, edgecolor='black')
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

# Boxplot for Fare
sns.boxplot(x=df['fare'])
plt.title('Fare Distribution')
plt.show()

# Correlation matrix
numeric_df = df.select_dtypes(include=['float64', 'int64'])
corr_matrix = numeric_df.corr()

sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

sns.pairplot(numeric_df)
plt.show()

sns.barplot(x='sex', y='survived', data=df)
plt.title('Survival Rate by Gender')
plt.show()

sns.violinplot(x='survived', y='age', data=df)
plt.title('Age Distribution by Survival')
plt.show()

